version: '2.1'

services:
  url-shortener:
    image: url-shortener
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 app.js